-- CREATE DATABASE EMPLOYEES;
USE EMPLOYEES;
CREATE TABLE employees (
    EMPLOYEE_ID CHAR(6) NOT NULL PRIMARY KEY,
    F_NAME CHAR(10),
    L_NAME CHAR(10), -- Specify CHAR data type here
    SSN INT NOT NULL,
    B_DATE VARCHAR(10), -- Specify a suitable length for the date field
    SEX CHAR(1),
    ADDRESS VARCHAR(50),
    JOB_ID INTEGER,
    SALARY INTEGER,
    MANAGER_ID INTEGER,
    DEP_ID INTEGER
);


INSERT INTO employees VALUES
('E1001','John','Thomas','123456','1976-01-09','M','5631 Rice, OakPark,JL','100','100001010','30001','2'),
('E1002','Alicw','James','123457','1972-07-31','F','980 Berry In,JL','200','809717832','30002','5'),
('E1003','Steve','Wells','123458','1980-08-10','M','291 Springs,Gary,JL','300','1309201','30003','5');
UPDATE employees SET ADDRESS ='5631 Rice, OakPark,JL' WHERE EMPLOYEE_ID='E1001';
UPDATE employees SET ADDRESS ='980 Berry In,Elgin,JL' WHERE EMPLOYEE_ID='E1002';
UPDATE employees SET ADDRESS ='291 Springs,Gary,JL' WHERE EMPLOYEE_ID='E1003';
UPDATE employees SET SALARY ='1000000' WHERE EMPLOYEE_ID='E1001';
UPDATE employees SET SALARY ='80000' WHERE EMPLOYEE_ID='E1002';
UPDATE employees SET SALARY ='50000' WHERE EMPLOYEE_ID='E1003';
ALTER TABLE employees ADD DEP_NAME CHAR(120);
UPDATE employees SET DEP_NAME = 'Architect Group' WHERE EMPLOYEE_ID='E1001';
UPDATE employees SET DEP_NAME = 'Software Development' WHERE EMPLOYEE_ID='E1002';
UPDATE employees SET DEP_NAME = 'Design Team' WHERE EMPLOYEE_ID='E1003';
-- SELECT * FROM employees;

-- String Patterns

-- SELECT F_NAME,L_NAME FROM employees WHERE ADDRESS LIKE '%JL%'
-- SELECT F_NAME,L_NAME FROM employees WHERE B_DATE LIKE '197%';
-- SELECT * FROM employees WHERE (SALARY BETWEEN 50000 AND 1000000) AND DEP_ID=5;

-- Sorting
-- SELECT F_NAME,L_NAME,DEP_ID FROM employees ORDER BY DEP_ID;
-- SELECT F_NAME,L_NAME,DEP_ID FROM employees ORDER BY DEP_ID DESC,L_NAME DESC ;
-- SELECT DEP_ID ,COUNT(*) FROM employees GROUP BY DEP_ID;
-- SELECT DEP_ID, COUNT(*), AVG(SALARY) FROM employees GROUP BY DEP_ID;

SELECT DEP_ID ,COUNT(*) as NUM_EMPLOYEES,AVG(SALARY) as AVG_SALARY FROM employees GROUP BY DEP_ID HAVING COUNT(*)<4 ORDER BY AVG_SALARY;


