-- USE PET;
-- SET SQL_SAFE_UPDATES = 0;
-- UPDATE PETSALE SET QUANTITY = 9 WHERE ID = 1;
-- UPDATE PETSALE SET QUANTITY = 3 WHERE ID = 2;
-- UPDATE PETSALE SET QUANTITY = 2 WHERE ID = 3;
-- UPDATE PETSALE SET QUANTITY = 6 WHERE ID = 4;
-- UPDATE PETSALE SET QUANTITY = 24 WHERE ID = 5;
ALTER TABLE employees ADD DEP_NAME CHAR(120);
-- SET SQL_SAFE_UPDATES = 1; -- Re-enable safe update mode
-- ALTER TABLE PETSALE DROP COLUMN PROFIT;
-- SELECT * FROM PETSALE;
-- ALTER TABLE PETSALE CHANGE PET  PET VARCHAR(20);
-- SELECT * FROM PETSALE;
-- ALTER TABLE `PETSALE` CHANGE `PET` `ANIMAL` varchar(20);

-- SELECT * FROM PETSALE;
-- TRUNCATE TABLE PET ;

-- SELECT * FROM PET;